"""
Django settings for project_arashi project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os

# === BASE DIR ===
BASE_DIR = Path(__file__).resolve().parent.parent


# === SECURITY ===
SECRET_KEY = 'django-insecure-k%gzt1yf#x_7k4nd75j2$lu-03k=p9o32v6gdo$-z!d&rmhg^e'
DEBUG = False

ALLOWED_HOSTS = [
    "arashi-yjjkg.onrender.com",
    "127.0.0.1",
    "localhost"
]

CSRF_TRUSTED_ORIGINS = [
    "https://arashi-yjjkg.onrender.com"
]


# === APPLICATIONS ===
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'arashi_yjjkg',
]


# === MIDDLEWARE ===
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # ← 静的ファイル配信用に追加！
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# === URL & WSGI ===
ROOT_URLCONF = 'project_arashi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_arashi.wsgi.application'


# === DATABASE ===
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# === PASSWORDS ===
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# === LANGUAGE & TIMEZONE ===
LANGUAGE_CODE = 'ja'
TIME_ZONE = 'Asia/Tokyo'
USE_I18N = True
USE_TZ = True


# === STATIC FILES ===
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # collectstaticで出力先
STATICFILES_DIRS = [
    BASE_DIR / 'arashi_yjjkg' / 'static',  # ← あなたの静的フォルダ
]

# whitenoise 用の設定（圧縮とキャッシュ対応）
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# === DEFAULT PK ===
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
